version: '3'

services:

  db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-kvitrvn}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kvitrvn}
      POSTGRES_USER: ${POSTGRES_USER:-kvitrvn}
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  web:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www:delegated
      - ./tools/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    user: '${USER_ID:-1000}:${GROUP_ID:-1000}'
    restart: unless-stopped
    image: kvitrvn/php:8.1.0
    volumes:
      - .:/var/www:delegated
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql://${POSTGRES_PASSWORD:-kvitrvn}:${POSTGRES_PASSWORD:-kvitrvn}@db:5432/${POSTGRES_DB:-kvitrvn}?serverVersion=15&chartset=utf8

  # DEV TOOLS
  

volumes:
  db-data:
