version: '3'
services:

  adminer:
    image: adminer
    environment:
      APP_ENV: dev
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8888:8080

  node:
    user: '${USER_ID:-1000}:${GROUP_ID:-1000}'
    build:
      context: ./tools/docker/node
    command: yarn run watch
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
